namespace SpriteKind {
    export const Punto = SpriteKind.create()
    export const Enemigo = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemigo, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    pause(500)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    game.gameOver(true)
})
let mySprite: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
let Supermann = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ..............eee...............
    .............eeeee..............
    ............ddddddd.............
    ............fffffff.............
    ............f1ff1ff.............
    ............fffffff.............
    ............ddddddd.............
    ............2ddddd2.............
    ...........288888882............
    ..........28888888882...........
    ..........2d8888888d2...........
    .........22d8888888d22..........
    .........22d8888888d22..........
    ........222d8888888d222.........
    ........2222fffffff2222.........
    .......22222fffffff22222........
    .......22222fffffff22222........
    .......22222fffffff22222........
    ............fffffff.............
    ...........fffffffff............
    ...........fffffffff............
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Player)
controller.moveSprite(Supermann)
tiles.placeOnRandomTile(Supermann, assets.tile`myTile`)
info.setLife(3)
let Rescatado = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . e e e . . . . . . . 
    . . . . . d d d d d . . . . . . 
    . . . . . d 1 d 1 d . . . . . . 
    . . . . . d d d d d . . . . . . 
    . . . . . . d d d . . . . . . . 
    . . . . . 7 7 7 7 7 . . . . . . 
    . . . . . 7 7 7 7 7 . . . . . . 
    . . . . . 7 7 7 7 7 . . . . . . 
    . . . . . 7 7 7 7 7 . . . . . . 
    . . . . . 7 7 7 7 7 . . . . . . 
    . . . . . f f f f f . . . . . . 
    . . . . . f f f f f . . . . . . 
    . . . . . f f f f f . . . . . . 
    . . . . b b b b b b b . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Punto)
let Autoo_Malo = sprites.create(img`
    . . . . . . . 8 8 8 8 8 . . . . 
    . . . . . 8 8 6 6 6 6 6 8 . . . 
    . . . . 8 8 6 6 6 6 6 6 6 8 . . 
    . . . . 8 9 7 7 7 6 6 6 7 b 8 . 
    . . 8 8 9 9 7 7 7 7 6 6 7 9 b 8 
    . 8 6 6 9 9 7 7 7 7 7 6 7 9 9 8 
    8 6 6 6 9 9 6 7 7 7 7 7 6 9 9 8 
    8 6 6 6 9 9 8 8 8 8 8 8 8 9 9 8 
    8 6 6 6 9 b 8 b b b 8 b 8 b 9 8 
    8 6 8 8 8 8 b b b b 8 b b 8 b 8 
    8 8 3 3 8 8 6 6 6 6 8 6 6 8 8 8 
    8 3 3 8 8 8 8 8 8 8 8 8 8 8 8 8 
    8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
    8 8 8 8 f f f 8 8 8 8 f f f 8 8 
    . 8 8 f f f b f 8 8 f f f b f . 
    . . . . c b b . . . . c b b . . 
    `, SpriteKind.Enemy)
tiles.placeOnRandomTile(Rescatado, sprites.vehicle.roadHorizontal)
tiles.placeOnRandomTile(Autoo_Malo, sprites.vehicle.roadTurn3)
Autoo_Malo.setVelocity(50, 0)
mySprite.setStayInScreen(true)
